### PR TITLE
port CSS

### PR DESCRIPTION
**Pull request by whellen0112**

### CODE REVIEW

**Review by Lucitic — COMMENTED** [review]
I feel like the links in href and src pieces in the .erb files should be relative not absolute. But we can fix that in a different story if need be.

**Comment by JDDelrosario** [comment]
> I feel like the links in href and src pieces in the .erb files should be relative not absolute. But we can fix that in a different story if need be.

This is one of the things that we need to fix in the "big refactor" in iteration 2: we should be using rails tags i.e. <% stylesheet="" %> and not directly editing HTML. Right now our app isn't properly "on rails" as much as it is "on top of rails", which is what we are aiming to fix

**Review by JDDelrosario — APPROVED** [review]
Approved to get the code base caught up - most of this will be refactored anyway.

**Comment by Lucitic** [comment]
okay if we're gonna refactor it anyway then I'll approve

**Comment by Lucitic** [comment]
my bad hit the wrong button

**Review by Lucitic — APPROVED** [review]
Looks good we'll fix the other part later

**Review by ChuanHuoGe — APPROVED** [review]
LGTM

**Comment by ethangnibus** [comment]
@JDDelrosario completely agree with using rails tags in the big refactor

**Comment by ethangnibus** [comment]
@whellen0112 looks good!

**Pull request merged**
