### PR TITLE
Port HTML Files

### PR DESCRIPTION
**Pull request by JDDelrosario**
Ported HTML files

### CODE REVIEW

**Comment by JDDelrosario** [comment]
WHEN REVIEWING PLEASE LOOK AT THE TOP FEW FILES AND THE BOTTOM FEW FILES. YOU CAN IGNORE THE FILES INBETWEEN.

**Comment by ChuanHuoGe** [comment]
LGTM

**Review by ChuanHuoGe — APPROVED** [review]

**Review by whellen0112 — APPROVED** [review]
Reviewed. Amazing work! :)

**Comment by ethangnibus** [comment]
Good work !

**Review by ethangnibus — COMMENTED** [review]
nice

**Pull request merged**
